package com.springmvc.OnlineMarketplace.Bean;
// Generated Dec 29, 2017 2:44:55 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProductSpecification generated by hbm2java
 */
@Entity
@Table(name = "ProductSpecification", catalog = "OnlineMarketplace")
public class ProductSpecification implements java.io.Serializable {

	private ProductSpecificationId id;
	private Integer value;
	private BigDecimal min;
	private BigDecimal max;

	public ProductSpecification() {
	}

	public ProductSpecification(ProductSpecificationId id) {
		this.id = id;
	}

	public ProductSpecification(ProductSpecificationId id, Integer value, BigDecimal min, BigDecimal max) {
		this.id = id;
		this.value = value;
		this.min = min;
		this.max = max;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "productId", nullable = false)),
			@AttributeOverride(name = "specId", column = @Column(name = "specId", nullable = false)) })
	public ProductSpecificationId getId() {
		return this.id;
	}

	public void setId(ProductSpecificationId id) {
		this.id = id;
	}

	@Column(name = "value")
	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	@Column(name = "min", precision = 6)
	public BigDecimal getMin() {
		return this.min;
	}

	public void setMin(BigDecimal min) {
		this.min = min;
	}

	@Column(name = "max", precision = 6)
	public BigDecimal getMax() {
		return this.max;
	}

	public void setMax(BigDecimal max) {
		this.max = max;
	}

}
