package com.springmvc.OnlineMarketplace.Bean;
// Generated Dec 29, 2017 2:44:55 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductSubCategory generated by hbm2java
 */
@Entity
@Table(name = "ProductSubCategory", catalog = "OnlineMarketplace")
public class ProductSubCategory implements java.io.Serializable {

	private Integer prodSubCategoryId;
	private String name;
	private String description;
	private Integer productCategoryId;

	public ProductSubCategory() {
	}

	public ProductSubCategory(String name, String description, Integer productCategoryId) {
		this.name = name;
		this.description = description;
		this.productCategoryId = productCategoryId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "prodSubCategoryId", unique = true, nullable = false)
	public Integer getProdSubCategoryId() {
		return this.prodSubCategoryId;
	}

	public void setProdSubCategoryId(Integer prodSubCategoryId) {
		this.prodSubCategoryId = prodSubCategoryId;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "productCategoryId")
	public Integer getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(Integer productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

}
