package com.springmvc.OnlineMarketplace.Bean;
// Generated Dec 29, 2017 2:44:55 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductDetail generated by hbm2java
 */
@Entity
@Table(name = "ProductDetail", catalog = "OnlineMarketplace")
public class ProductDetail implements java.io.Serializable {

	private Integer prodDetailId;
	private Integer productId;
	private String shortDescription;
	private String description;

	public ProductDetail() {
	}

	public ProductDetail(Integer productId, String shortDescription, String description) {
		this.productId = productId;
		this.shortDescription = shortDescription;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "prodDetailId", unique = true, nullable = false)
	public Integer getProdDetailId() {
		return this.prodDetailId;
	}

	public void setProdDetailId(Integer prodDetailId) {
		this.prodDetailId = prodDetailId;
	}

	@Column(name = "productId")
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "shortDescription", length = 100)
	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	@Column(name = "description", length = 400)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
