// default package
// Generated Dec 29, 2017 12:52:29 PM by Hibernate Tools 4.3.1.Final
package com.springmvc.OnlineMarketplace.Bean;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductSubCategory generated by hbm2java
 */
@Entity
@Table(name = "ProductSubCategory", schema = "dbo", catalog = "ProjectDepot")
public class ProductSubCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int prodSubCategoryId;
	private ProductCategory productCategory;
	private String name;
	private String descrption;

	private Set<SubCategorySpecification> subCategorySpecifications = new HashSet<SubCategorySpecification>(0);

	public ProductSubCategory() {
	}

	public ProductSubCategory(int prodSubCategoryId) {
		this.prodSubCategoryId = prodSubCategoryId;
	}

	public ProductSubCategory(int prodSubCategoryId, ProductCategory productCategory, String name, String descrption,
			 Set<SubCategorySpecification> subCategorySpecifications) {
		this.prodSubCategoryId = prodSubCategoryId;
		this.productCategory = productCategory;
		this.name = name;
		this.descrption = descrption;
		
		this.subCategorySpecifications = subCategorySpecifications;
	}

	@Id

	@Column(name = "prodSubCategoryId", unique = true, nullable = false)
	public int getProdSubCategoryId() {
		return this.prodSubCategoryId;
	}

	public void setProdSubCategoryId(int prodSubCategoryId) {
		this.prodSubCategoryId = prodSubCategoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productCategoryId")
	public ProductCategory getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(ProductCategory productCategory) {
		this.productCategory = productCategory;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "descrption", length = 200)
	public String getDescrption() {
		return this.descrption;
	}

	public void setDescrption(String descrption) {
		this.descrption = descrption;
	}



	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productSubCategory")
	public Set<SubCategorySpecification> getSubCategorySpecifications() {
		return this.subCategorySpecifications;
	}

	public void setSubCategorySpecifications(Set<SubCategorySpecification> subCategorySpecifications) {
		this.subCategorySpecifications = subCategorySpecifications;
	}

}
