// default package
// Generated Dec 29, 2017 12:52:29 PM by Hibernate Tools 4.3.1.Final
package com.springmvc.OnlineMarketplace.Bean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductDetail generated by hbm2java
 */
@Entity
@Table(name = "ProductDetail", schema = "dbo", catalog = "ProjectDepot")
public class ProductDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int prodDetailId;
	private Product product;
	private String shortDescription;
	private String description;

	public ProductDetail() {
	}

	public ProductDetail(int prodDetailId) {
		this.prodDetailId = prodDetailId;
	}

	public ProductDetail(int prodDetailId, Product product, String shortDescription, String description) {
		this.prodDetailId = prodDetailId;
		this.product = product;
		this.shortDescription = shortDescription;
		this.description = description;
	}

	@Id

	@Column(name = "prodDetailId", unique = true, nullable = false)
	public int getProdDetailId() {
		return this.prodDetailId;
	}

	public void setProdDetailId(int prodDetailId) {
		this.prodDetailId = prodDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "shortDescription", length = 100)
	public String getShortDescription() {
		return this.shortDescription;
	}

	public void setShortDescription(String shortDescription) {
		this.shortDescription = shortDescription;
	}

	@Column(name = "description", length = 400)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
