// default package
// Generated Dec 29, 2017 12:52:29 PM by Hibernate Tools 4.3.1.Final
package com.springmvc.OnlineMarketplace.Bean;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductSpecification generated by hbm2java
 */
@Entity
@Table(name = "ProductSpecification", schema = "dbo", catalog = "ProjectDepot")
public class ProductSpecification implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProductSpecificationId id;
	private Product product;
	private Specification specification;
	private Integer value;
	private Integer min;
	private Integer max;

	public ProductSpecification() {
	}

	public ProductSpecification(ProductSpecificationId id, Product product, Specification specification) {
		this.id = id;
		this.product = product;
		this.specification = specification;
	}

	public ProductSpecification(ProductSpecificationId id, Product product, Specification specification, Integer value,
			Integer min, Integer max) {
		this.id = id;
		this.product = product;
		this.specification = specification;
		this.value = value;
		this.min = min;
		this.max = max;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "productId", nullable = false)),
			@AttributeOverride(name = "specId", column = @Column(name = "specId", nullable = false)) })
	public ProductSpecificationId getId() {
		return this.id;
	}

	public void setId(ProductSpecificationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "specId", nullable = false, insertable = false, updatable = false)
	public Specification getSpecification() {
		return this.specification;
	}

	public void setSpecification(Specification specification) {
		this.specification = specification;
	}

	@Column(name = "value")
	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

	@Column(name = "min")
	public Integer getMin() {
		return this.min;
	}

	public void setMin(Integer min) {
		this.min = min;
	}

	@Column(name = "max")
	public Integer getMax() {
		return this.max;
	}

	public void setMax(Integer max) {
		this.max = max;
	}

}
