// default package
// Generated Dec 29, 2017 12:52:29 PM by Hibernate Tools 4.3.1.Final
package com.springmvc.OnlineMarketplace.Bean;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductSpecificationId generated by hbm2java
 */
@Embeddable
public class ProductSpecificationId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int productId;
	private int specId;

	public ProductSpecificationId() {
	}

	public ProductSpecificationId(int productId, int specId) {
		this.productId = productId;
		this.specId = specId;
	}

	@Column(name = "productId", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "specId", nullable = false)
	public int getSpecId() {
		return this.specId;
	}

	public void setSpecId(int specId) {
		this.specId = specId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductSpecificationId))
			return false;
		ProductSpecificationId castOther = (ProductSpecificationId) other;

		return (this.getProductId() == castOther.getProductId()) && (this.getSpecId() == castOther.getSpecId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getSpecId();
		return result;
	}

}
