// default package
// Generated Dec 29, 2017 12:52:29 PM by Hibernate Tools 4.3.1.Final
package com.springmvc.OnlineMarketplace.Bean;


import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.Id;

import javax.persistence.Table;

/**
 * ProductCategory generated by hbm2java
 */
@Entity
@Table(name = "ProductCategory", schema = "dbo", catalog = "ProjectDepot")
public class ProductCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int productCategoryId;
	private String name;
	private String descreption;


	public ProductCategory() {
	}

	public ProductCategory(int productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	public ProductCategory(int productCategoryId, String name, String descreption) {
		this.productCategoryId = productCategoryId;
		this.name = name;
		this.descreption = descreption;
	}

	@Id

	@Column(name = "productCategoryId", unique = true, nullable = false)
	public int getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(int productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "descreption", length = 200)
	public String getDescreption() {
		return this.descreption;
	}

	public void setDescreption(String descreption) {
		this.descreption = descreption;
	}


}
