package com.springmvc.OnlineMarketplace.Bean;
// Generated Dec 29, 2017 2:44:55 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product", catalog = "OnlineMarketplace")
public class Product implements java.io.Serializable {

	private Integer productId;
	private Integer prodSubCategoryId;
	private String manufacture;
	private String series;
	private String model;
	private String useType;
	private String application;
	private String mountingLocation;
	private String accessories;
	private String modelYear;
	private String image;

	public Product() {
	}

	public Product(Integer prodSubCategoryId, String manufacture, String series, String model, String useType,
			String application, String mountingLocation, String accessories, String modelYear, String image) {
		this.prodSubCategoryId = prodSubCategoryId;
		this.manufacture = manufacture;
		this.series = series;
		this.model = model;
		this.useType = useType;
		this.application = application;
		this.mountingLocation = mountingLocation;
		this.accessories = accessories;
		this.modelYear = modelYear;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "productId", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "prodSubCategoryId")
	public Integer getProdSubCategoryId() {
		return this.prodSubCategoryId;
	}

	public void setProdSubCategoryId(Integer prodSubCategoryId) {
		this.prodSubCategoryId = prodSubCategoryId;
	}

	@Column(name = "manufacture", length = 50)
	public String getManufacture() {
		return this.manufacture;
	}

	public void setManufacture(String manufacture) {
		this.manufacture = manufacture;
	}

	@Column(name = "series", length = 20)
	public String getSeries() {
		return this.series;
	}

	public void setSeries(String series) {
		this.series = series;
	}

	@Column(name = "model", length = 30)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "useType", length = 20)
	public String getUseType() {
		return this.useType;
	}

	public void setUseType(String useType) {
		this.useType = useType;
	}

	@Column(name = "application", length = 20)
	public String getApplication() {
		return this.application;
	}

	public void setApplication(String application) {
		this.application = application;
	}

	@Column(name = "mountingLocation", length = 10)
	public String getMountingLocation() {
		return this.mountingLocation;
	}

	public void setMountingLocation(String mountingLocation) {
		this.mountingLocation = mountingLocation;
	}

	@Column(name = "accessories", length = 50)
	public String getAccessories() {
		return this.accessories;
	}

	public void setAccessories(String accessories) {
		this.accessories = accessories;
	}

	@Column(name = "modelYear", length = 10)
	public String getModelYear() {
		return this.modelYear;
	}

	public void setModelYear(String modelYear) {
		this.modelYear = modelYear;
	}

	@Column(name = "image", length = 1024)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
