// default package
// Generated Dec 29, 2017 12:52:29 PM by Hibernate Tools 4.3.1.Final
package com.springmvc.OnlineMarketplace.Bean;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectDetails generated by hbm2java
 */
@Entity
@Table(name = "ProjectDetails", schema = "dbo", catalog = "ProjectDepot")
public class ProjectDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProjectDetailsId id;
	private Product product;
	private Project project;
	private Integer quantity;
	private BigDecimal priceQuote;

	public ProjectDetails() {
	}

	public ProjectDetails(ProjectDetailsId id, Product product, Project project) {
		this.id = id;
		this.product = product;
		this.project = project;
	}

	public ProjectDetails(ProjectDetailsId id, Product product, Project project, Integer quantity,
			BigDecimal priceQuote) {
		this.id = id;
		this.product = product;
		this.project = project;
		this.quantity = quantity;
		this.priceQuote = priceQuote;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "projectId", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "productId", nullable = false)) })
	public ProjectDetailsId getId() {
		return this.id;
	}

	public void setId(ProjectDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projectId", nullable = false, insertable = false, updatable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "priceQuote", precision = 6)
	public BigDecimal getPriceQuote() {
		return this.priceQuote;
	}

	public void setPriceQuote(BigDecimal priceQuote) {
		this.priceQuote = priceQuote;
	}

}
