package com.springmvc.OnlineMarketplace.Bean;
// Generated Dec 29, 2017 2:44:55 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProjectDetails generated by hbm2java
 */
@Entity
@Table(name = "ProjectDetails", catalog = "OnlineMarketplace")
public class ProjectDetails implements java.io.Serializable {

	private ProjectDetailsId id;
	private Integer quantity;
	private BigDecimal priceQuote;

	public ProjectDetails() {
	}

	public ProjectDetails(ProjectDetailsId id) {
		this.id = id;
	}

	public ProjectDetails(ProjectDetailsId id, Integer quantity, BigDecimal priceQuote) {
		this.id = id;
		this.quantity = quantity;
		this.priceQuote = priceQuote;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "projectId", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "productId", nullable = false)) })
	public ProjectDetailsId getId() {
		return this.id;
	}

	public void setId(ProjectDetailsId id) {
		this.id = id;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "priceQuote", precision = 6)
	public BigDecimal getPriceQuote() {
		return this.priceQuote;
	}

	public void setPriceQuote(BigDecimal priceQuote) {
		this.priceQuote = priceQuote;
	}

}
