// default package
// Generated Dec 29, 2017 12:52:29 PM by Hibernate Tools 4.3.1.Final
package com.springmvc.OnlineMarketplace.Bean;
import java.math.BigDecimal;

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "Project", schema = "dbo", catalog = "ProjectDepot")
public class Project implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int projectId;
	private UserDb userDb;
	private String projectName;
	private String projectAddress;
	private String projectType;
	private BigDecimal projectSize;
	private String clientName;
	

	public Project() {
	}

	public Project(int projectId) {
		this.projectId = projectId;
	}

	public Project(int projectId, UserDb userDb, String projectName, String projectAddress, String projectType,
			BigDecimal projectSize, String clientName, Set<ProjectDetails> projectDetailses) {
		this.projectId = projectId;
		this.userDb = userDb;
		this.projectName = projectName;
		this.projectAddress = projectAddress;
		this.projectType = projectType;
		this.projectSize = projectSize;
		this.clientName = clientName;
	
	}

	@Id

	@Column(name = "projectId", unique = true, nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId")
	public UserDb getUserDb() {
		return this.userDb;
	}

	public void setUserDb(UserDb userDb) {
		this.userDb = userDb;
	}

	@Column(name = "projectName", length = 50)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "projectAddress", length = 100)
	public String getProjectAddress() {
		return this.projectAddress;
	}

	public void setProjectAddress(String projectAddress) {
		this.projectAddress = projectAddress;
	}

	@Column(name = "projectType", length = 10)
	public String getProjectType() {
		return this.projectType;
	}

	public void setProjectType(String projectType) {
		this.projectType = projectType;
	}

	@Column(name = "projectSize", precision = 6)
	public BigDecimal getProjectSize() {
		return this.projectSize;
	}

	public void setProjectSize(BigDecimal projectSize) {
		this.projectSize = projectSize;
	}

	@Column(name = "clientName", length = 30)
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}



}
