package com.springmvc.OnlineMarketplace.Bean;
// Generated Dec 29, 2017 2:44:55 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectDetailsId generated by hbm2java
 */
@Embeddable
public class ProjectDetailsId implements java.io.Serializable {

	private int projectId;
	private int productId;

	public ProjectDetailsId() {
	}

	public ProjectDetailsId(int projectId, int productId) {
		this.projectId = projectId;
		this.productId = productId;
	}

	@Column(name = "projectId", nullable = false)
	public int getProjectId() {
		return this.projectId;
	}

	public void setProjectId(int projectId) {
		this.projectId = projectId;
	}

	@Column(name = "productId", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectDetailsId))
			return false;
		ProjectDetailsId castOther = (ProjectDetailsId) other;

		return (this.getProjectId() == castOther.getProjectId()) && (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
