package com.springmvc.OnlineMarketplace.Bean;
// Generated Dec 29, 2017 2:44:55 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "Project", catalog = "OnlineMarketplace")
public class Project implements java.io.Serializable {

	private Integer projectId;
	private String projectName;
	private String projectAddress;
	private String projectType;
	private BigDecimal projectSize;
	private String clientName;
	private Integer userId;

	public Project() {
	}

	public Project(String projectName, String projectAddress, String projectType, BigDecimal projectSize,
			String clientName, Integer userId) {
		this.projectName = projectName;
		this.projectAddress = projectAddress;
		this.projectType = projectType;
		this.projectSize = projectSize;
		this.clientName = clientName;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "projectId", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "projectName", length = 50)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "projectAddress", length = 100)
	public String getProjectAddress() {
		return this.projectAddress;
	}

	public void setProjectAddress(String projectAddress) {
		this.projectAddress = projectAddress;
	}

	@Column(name = "projectType", length = 10)
	public String getProjectType() {
		return this.projectType;
	}

	public void setProjectType(String projectType) {
		this.projectType = projectType;
	}

	@Column(name = "projectSize", precision = 6)
	public BigDecimal getProjectSize() {
		return this.projectSize;
	}

	public void setProjectSize(BigDecimal projectSize) {
		this.projectSize = projectSize;
	}

	@Column(name = "clientName", length = 30)
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
