package com.springmvc.OnlineMarketplace.Bean;
// Generated Dec 29, 2017 2:44:55 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Specification generated by hbm2java
 */
@Entity
@Table(name = "Specification", catalog = "OnlineMarketplace")
public class Specification implements java.io.Serializable {

	private Integer specId;
	private String name;
	private String description;

	public Specification() {
	}

	public Specification(String name, String description) {
		this.name = name;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "specId", unique = true, nullable = false)
	public Integer getSpecId() {
		return this.specId;
	}

	public void setSpecId(Integer specId) {
		this.specId = specId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
