// default package
// Generated Dec 29, 2017 12:52:29 PM by Hibernate Tools 4.3.1.Final
package com.springmvc.OnlineMarketplace.Bean;

import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.Id;

import javax.persistence.Table;

/**
 * Specification generated by hbm2java
 */
@Entity
@Table(name = "Specification", schema = "dbo", catalog = "ProjectDepot")
public class Specification implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int specId;
	private String name;
	private String description;

	

	public Specification() {
	}

	public Specification(int specId) {
		this.specId = specId;
	}

	public Specification(int specId, String name, String description
			) {
		this.specId = specId;
		this.name = name;
		this.description = description;
	
	}

	@Id

	@Column(name = "specId", unique = true, nullable = false)
	public int getSpecId() {
		return this.specId;
	}

	public void setSpecId(int specId) {
		this.specId = specId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	

}
