// default package
// Generated Dec 29, 2017 12:52:29 PM by Hibernate Tools 4.3.1.Final
package com.springmvc.OnlineMarketplace.Bean;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SubCategorySpecification generated by hbm2java
 */
@Entity
@Table(name = "SubCategorySpecification", schema = "dbo", catalog = "ProjectDepot")
public class SubCategorySpecification implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private SubCategorySpecificationId id;
	private ProductSubCategory productSubCategory;
	private Specification specification;
	private Integer min;
	private Integer max;

	public SubCategorySpecification() {
	}

	public SubCategorySpecification(SubCategorySpecificationId id, ProductSubCategory productSubCategory,
			Specification specification) {
		this.id = id;
		this.productSubCategory = productSubCategory;
		this.specification = specification;
	}

	public SubCategorySpecification(SubCategorySpecificationId id, ProductSubCategory productSubCategory,
			Specification specification, Integer min, Integer max) {
		this.id = id;
		this.productSubCategory = productSubCategory;
		this.specification = specification;
		this.min = min;
		this.max = max;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "prodSubCategoryId", column = @Column(name = "prodSubCategoryId", nullable = false)),
			@AttributeOverride(name = "specId", column = @Column(name = "specId", nullable = false)) })
	public SubCategorySpecificationId getId() {
		return this.id;
	}

	public void setId(SubCategorySpecificationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prodSubCategoryId", nullable = false, insertable = false, updatable = false)
	public ProductSubCategory getProductSubCategory() {
		return this.productSubCategory;
	}

	public void setProductSubCategory(ProductSubCategory productSubCategory) {
		this.productSubCategory = productSubCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "specId", nullable = false, insertable = false, updatable = false)
	public Specification getSpecification() {
		return this.specification;
	}

	public void setSpecification(Specification specification) {
		this.specification = specification;
	}

	@Column(name = "min")
	public Integer getMin() {
		return this.min;
	}

	public void setMin(Integer min) {
		this.min = min;
	}

	@Column(name = "max")
	public Integer getMax() {
		return this.max;
	}

	public void setMax(Integer max) {
		this.max = max;
	}

}
